### ISSUE TITLE
vl crashes after successfully image download

### ISSUE THREAD

**Issue by BubaVV** [virt-lightning/virt-lightning#218]
Steps to reproduce:

1. Create yaml requiring non-existing locally image, i.e. ubuntu-18.04
2. do `$ vl up`
vl crashes after successful image download:

```
$ vl up                                                                                                                                
downloading image from: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img                                                                                                    
Image ubuntu-18.04 is ready!                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                         
  File "/home/vmarkov/.local/bin/vl", line 8, in <module>                                                                                                                                                  
    sys.exit(main())                                                                                                                                                                                       
  File "/home/vmarkov/.local/lib/python3.8/site-packages/virt_lightning/shell.py", line 362, in main                                                                                                       
    action_func(configuration=configuration, **vars(args))                                                                                                                                                 
  File "/home/vmarkov/.local/lib/python3.8/site-packages/virt_lightning/api.py", line 184, in up                                                                                                           
    _ensure_image_exists(hv, virt_lightning_yaml)                                                                                                                                                          
  File "/home/vmarkov/.local/lib/python3.8/site-packages/virt_lightning/api.py", line 150, in _ensure_image_exists                                                                                         
    if distro not in hv.distro_available():                                                                                                                                                                
  File "/home/vmarkov/.local/lib/python3.8/site-packages/virt_lightning/virt_lightning.py", line 639, in distro_available                                                                                  
    path = self.get_storage_dir() / "upstream"                                                                                                                                                             
  File "/home/vmarkov/.local/lib/python3.8/site-packages/virt_lightning/virt_lightning.py", line 195, in get_storage_dir                                                                                   
    xml = self.storage_pool_obj.XMLDesc(0)                                                                                                                                                                 
  File "/usr/lib/python3/dist-packages/libvirt.py", line 3490, in XMLDesc                                                                                                                                  
    if ret is None: raise libvirtError ('virStoragePoolGetXMLDesc() failed', pool=self)                                                                                                                    
libvirt.libvirtError: Cannot write data: Broken pipe
```

3. run `$ vl up` one more time, it finishes successfully, and doesn't mention image download stage

**Comment by goneri** [comment]
Hi @BubaVV,

Thanks for the bug report. Can you please try this fix: https://github.com/virt-lightning/virt-lightning/pull/219

**Comment by BubaVV** [comment]
Tested a bit. Seems that 2.1.0, master and proposed patch sometimes fail with the same trace. Tried to manually run `vl up; vl down; rm /var/lib/virt-lightning/pool/upstream/*` several times in a row

**Comment by goneri** [comment]
Ok, thanks @BubaVV.

**Comment by jbpratt** [comment]
Just hit a similar error. Applying the patch in 62ce95e worked as expected.
```
❯ vl up
downloading image from: https://object-storage.public.mtl1.vexxhost.net/swift/v1/1dbafeefbd4f4c80864414a441e72dd2/bsd-cloud-image.org/images/openbsd/6.9/openbsd-6.9.qcow2
downloading image from: https://object-storage.public.mtl1.vexxhost.net/swift/v1/1dbafeefbd4f4c80864414a441e72dd2/bsd-cloud-image.org/images/openbsd/6.9/openbsd-6.9.yaml
Image openbsd-6.9 is ready!
Traceback (most recent call last):
  File "/home/jbpratt/.local/bin/vl", line 8, in <module>
    sys.exit(main())
  File "/home/jbpratt/.local/lib/python3.9/site-packages/virt_lightning/shell.py", line 362, in main
    action_func(configuration=configuration, **vars(args))
  File "/home/jbpratt/.local/lib/python3.9/site-packages/virt_lightning/api.py", line 206, in up
    loop.run_until_complete(deploy())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jbpratt/.local/lib/python3.9/site-packages/virt_lightning/api.py", line 198, in deploy
    await f
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jbpratt/.local/lib/python3.9/site-packages/virt_lightning/api.py", line 91, in _start_domain
    domain = hv.get_domain_by_name(host["name"])
  File "/home/jbpratt/.local/lib/python3.9/site-packages/virt_lightning/virt_lightning.py", line 166, in get_domain_by_name
    dom = self.conn.lookupByName(name)
  File "/usr/lib/python3.9/site-packages/libvirt.py", line 4886, in lookupByName
    raise libvirtError('virDomainLookupByName() failed')
libvirt.libvirtError: Cannot write data: Broken pipe
```

**Comment by BubaVV** [comment]
Issue is still here. It is not depend on timeout of connection - even freshly recreated conn object may fail like in https://github.com/virt-lightning/virt-lightning/issues/218#issuecomment-991606086 . isAlive() method may provide false true answer and not reliable for conn state detection. Thread safety is also not an answer - converted deploy() to full sync and non-threaded function, and get the same error.

Possible solution might by moving connection (re)opening to LibvirtHypervisor class, but it leads to major refactor and stronger binding between api and the rest of code

**Comment by goneri** [comment]
@BubaVV  Can you reproduce the issue with a more up to date version of Libvirt? My understanding is that the issue was fixed by Libvirt and it makes little sense to put too much energy in building a workaround. In addition, the issue is not critical.

**Comment by BubaVV** [comment]
Ubuntu 22.04.5 as a host system, libvirt and libvirt-python are 8.0.0. Previous iteration of issue was reproduced on 20.04. Also will try to test on 24.04

**Comment by goneri** [comment]
Another fix/workaround is to catch the `libvirt.libvirtError: Cannot write data: Broken pipe` exception and trigger a reconnect in this case. @BubaVV would you be interested to try that?

**Comment by BubaVV** [comment]
Sure, yes
