### ISSUE TITLE
py3.10: TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary

### ISSUE THREAD

**Issue by jbpratt** [virt-lightning/virt-lightning#221]
```
❯ vl up
Traceback (most recent call last):
  File "/home/jbpratt/.local/bin/vl", line 8, in <module>
    sys.exit(main())
  File "/home/jbpratt/.local/lib/python3.10/site-packages/virt_lightning/shell.py", line 362, in main
    action_func(configuration=configuration, **vars(args))
  File "/home/jbpratt/.local/lib/python3.10/site-packages/virt_lightning/api.py", line 168, in up
    _register_aio_virt_impl(loop)
  File "/home/jbpratt/.local/lib/python3.10/site-packages/virt_lightning/api.py", line 68, in _register_aio_virt_impl
    libvirtaio.virEventRegisterAsyncIOImpl(loop=loop)
  File "/home/jbpratt/.local/lib/python3.10/site-packages/libvirtaio.py", line 462, in virEventRegisterAsyncIOImpl
    _current_impl = virEventAsyncIOImpl(loop=loop).register()
  File "/home/jbpratt/.local/lib/python3.10/site-packages/libvirtaio.py", line 277, in __init__
    self._finished = asyncio.Event(loop=loop)
  File "/usr/lib/python3.10/asyncio/locks.py", line 167, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
```

Exception thrown in the virt-python dependency. Issue has been opened here https://gitlab.com/libvirt/libvirt-python/-/issues/10

**Comment by goneri** [comment]
Thank you @jbpratt!

**Comment by jbpratt** [comment]
There is an MR on gitlab (the GitHub repo is a read-only mirror) for this issue https://gitlab.com/libvirt/libvirt-python/-/merge_requests/75
