### ISSUE TITLE
VM starting with non-existent network results in non-handled error

### ISSUE THREAD

**Issue by BubaVV** [virt-lightning/virt-lightning#312]
Reproduced on current main

virt-lightning.yaml:
```- name: test_1
  distro: ubuntu-22.04
  memory: 1024
  root_disk_size: 10
  vcpus: 1
  networks:
    - network: test-vl
    - network: test-2
```

`vl up` log:

```$ vl up
⚡ test_1
Traceback (most recent call last):
  File "/home/vv/git/tools/virt-lightning/env/bin/vl", line 8, in <module>
    sys.exit(main())
  File "/home/vv/git/tools/virt-lightning/virt_lightning/shell.py", line 380, in main
    action_func(configuration=configuration, **vars(args))
  File "/home/vv/git/tools/virt-lightning/virt_lightning/api.py", line 217, in up
    loop.run_until_complete(deploy())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/vv/git/tools/virt-lightning/virt_lightning/api.py", line 209, in deploy
    await f
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vv/git/tools/virt-lightning/virt_lightning/api.py", line 132, in _start_domain
    network["mac"] = hv.reuse_mac_address(
  File "/home/vv/git/tools/virt-lightning/virt_lightning/virt_lightning.py", line 586, in reuse_mac_address
    for lease in network_obj.DHCPLeases():
AttributeError: 'NoneType' object has no attribute 'DHCPLeases'
```

It was a part of testing related to https://github.com/virt-lightning/virt-lightning/pull/311 .

Possible measures:
1. Create all requested networks silently, if they not exist
2. Check their availability before VM create and fail gracefully
3. Document it as a feature in Readme

**Comment by goneri** [comment]
`2.` sounds like the best option to me. Which one do you prefer?

**Comment by BubaVV** [comment]
Also agree. It is aligned with default policy relating `virt-lightning` network, redefined for a single VM when needed. Try to push a PR during this week

**Comment by BubaVV** [comment]
As usual, I stumbled into the pitfall during my investigation. To create network, we need to pass cidr for it. For default network we have default value, but for user-defined it should be somewhere in separate parameter

**Comment by goneri** [comment]
> As usual, I stumbled into the pitfall during my investigation. To create network, we need to pass cidr for it. For default network we have default value, but for user-defined it should be somewhere in separate parameter

So do you raise an error if the CIDR is missing?

**Comment by BubaVV** [comment]
Here we have some discrepancy - LibvirtHypervisor supports only single network defined by config and ensured by init_network(). However, networks attached at instance startup are attached to existing domain without validation. At least, it gives us some inequality of default network and per-machine one. In my opinion, it is better to validate networks during _start_domain() and probably ensure their cleanup at instance destroy. If such workflow is ok, i'll also review required parameters for network create, like cidr

**Comment by goneri** [comment]
@BubaVV I agree with you. It makes little sense to have two different places where we check the network configuration.
