### ISSUE TITLE
Support ED25519 keys

### ISSUE THREAD

**Issue by perlun** [virt-lightning/virt-lightning#320]
Hi,

Thanks for a nice and interesting tool indeed. :pray: When trying to use it now on a new machine I'm setting up, I ran into this error:

```
$ vl up
⚡ netbsd-100-ufs 
Can not read ~/.ssh/id_rsa.pub. If you don't have any SSH key, please follow the steps describe here:
  https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key
Traceback (most recent call last):
  File "/home/per/.local/bin/vl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/per/.local/pipx/venvs/virt-lightning/lib/python3.11/site-packages/virt_lightning/shell.py", line 378, in main
    action_func(configuration=configuration, **vars(args))
  File "/home/per/.local/pipx/venvs/virt-lightning/lib/python3.11/site-packages/virt_lightning/api.py", line 219, in up
    loop.run_until_complete(deploy())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/per/.local/pipx/venvs/virt-lightning/lib/python3.11/site-packages/virt_lightning/api.py", line 211, in deploy
    await f
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/per/.local/pipx/venvs/virt-lightning/lib/python3.11/site-packages/virt_lightning/api.py", line 124, in _start_domain
    hv.configure_domain(domain, user_config)
  File "/home/per/.local/pipx/venvs/virt-lightning/lib/python3.11/site-packages/virt_lightning/virt_lightning.py", line 134, in configure_domain
    domain.load_ssh_key_file(pathlib.Path(config["ssh_key_file"]))
  File "/home/per/.local/pipx/venvs/virt-lightning/lib/python3.11/site-packages/virt_lightning/virt_lightning.py", line 720, in load_ssh_key_file
    self.ssh_key = ssh_key_file.expanduser().read_text()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1045, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/per/.ssh/id_rsa.pub'
```

My SSH key does indeed exist, but I created it using the ED25519 format and hence it is located in `~/.ssh/id_ed25519.pub`. In fact, this is the format suggested to be used by the GitHub docs page linked to there: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key

This is not the end of the world for me; I'll just create an RSA keypair now instead. But perhaps this would be worth looking into at some point since ED25519 are generally highly regarded, AFAIK. Thanks! :slightly_smiling_face:

**Comment by BubaVV** [comment]
You can setup it via global `config.ini` file, or per-machine option in yaml

**Comment by perlun** [comment]
Sounds good. I think it could make sense to keep this issue open to potentially auto-detect such keys in the future, unless you disagree.

**Comment by goneri** [comment]
> Sounds good. I think it could make sense to keep this issue open to potentially auto-detect such keys in the future, unless you disagree.

Yes, indeed. We should do something like this by default if `ssh_key_file` is not set:

```
>>> from pathlib import Path
>>> list((Path.home() / ".ssh").glob("*.pub"))
[PosixPath('/var/home/goneri/.ssh/id_ed25519.pub')]
```
