### ISSUE TITLE
Ubuntu 18.04 not found /etc/qemu/bridge.conf on up

### ISSUE THREAD

**Issue by zloidemon** [virt-lightning/virt-lightning#56]
Not found /etc/qemu/bridge.conf

```
 %> vl up
Starting:centos7
Traceback (most recent call last):
  File "/home/vg/Devel/virt-lightning/tmp/.venv/bin/vl", line 11, in <module>
    load_entry_point('virt-lightning', 'console_scripts', 'vl')()
  File "/home/vg/Devel/virt-lightning/virt_lightning/shell.py", line 331, in main
    globals()[args.action](configuration=configuration, **vars(args))
  File "/home/vg/Devel/virt-lightning/virt_lightning/shell.py", line 61, in up
    hv.start(domain)
  File "/home/vg/Devel/virt-lightning/virt_lightning/virt_lightning.py", line 189, in start
    domain.dom.create()
  File "/home/vg/Devel/virt-lightning/tmp/.venv/lib/python3.6/site-packages/libvirt.py", line 1068, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: internal error: /usr/lib/qemu/qemu-bridge-helper --use-vnet --br=virbr0 --fd=25: failed to communicate with bridge helper: Transport endpoint is not connected
stderr=failed to parse default acl file `/etc/qemu/bridge.conf'

```

System:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

Also has installed `bridge-utils`.

**Comment by goneri** [comment]
Are you using `qemu:///session`, this won't work on Ubuntu.

**Comment by goneri** [comment]
Hi @zloidemon,

I close the issue for now, please reopen if you can reproduce with the 1.0.0.

**Comment by sebma** [comment]
@zloidemon Here's what I did on my Ubuntu Trusty host to generate the `/etc/qemu/bridge.conf` file : 
```bash
$ bridgeInterface=$(\ls /sys/class/net | egrep -v "(eth|wlan|tap)[0-9]|lo")
$ echo allow $bridgeInterface | sudo tee -a /etc/qemu/bridge.conf
allow virbr0
```
Take a look at [this](https://wiki.qemu.org/Features/HelperNetworking) for more information.
